### ISSUE TITLE
Steam link is invalid, update readme with information on what this does?

### ISSUE THREAD

**Issue by draconb** [StarCpt/SE-GridFilter#1]
The link to steam leads to a removed page and no info is given about what this plugin does.

**Comment by khamseen** [comment]
Yeah I'd appreciate this, I keep forgetting the option for grid name filtering.

**Comment by StarCpt** [comment]
[added wayback machine link and usage instructions from the workshop page](https://github.com/StarCpt/SE-GridFilter/commit/66c6c0781ecc8f5334ec0eb53c0baf32738ed613)

**Comment by khamseen** [comment]
Nice, thanks! Also thanks for porting the plugin, it is yet another essential these days.
